name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd portfolio && npm install

      - name: Build Angular project
        run: cd portfolio && npm run build:ghpages

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Build: Update docs folder from Angular build" && git push)
